openmetadata:
  config:
    database:
      port: 5432
      driverClass: org.postgresql.Driver
      dbScheme: postgresql
      databaseName: openmetadata_db
      auth:
        username: openmetadata
        password:
          secretRef: sql-secrets
          secretKey: openmetadata-sql-password
    elasticsearch:
      searchType: opensearch
      port: 9200
      scheme: https
      connectionTimeoutSecs: 5
      socketTimeoutSecs: 60
      keepAliveTimeoutSecs: 600
      batchSize: 10
      auth:
        enabled: true
        username: openmetadata
        password:
          secretRef: elasticsearch-secrets
          secretKey: openmetadata-elasticsearch-password
    pipelineServiceClientConfig:
      apiEndpoint: http://openmetadata-dependencies-web.openmetadata.svc.cluster.local:8080
      metadataApiEndpoint: http://openmetadata.openmetadata.svc.cluster.local:8585/api
service:
  type: LoadBalancer
